<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.ds</groupId>
    <artifactId>datastructure</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <modules>
        <module>a_Fundamentals</module>
        <module>a_Fundamentals/a_Premitives</module>
        <module>a_Fundamentals/b_Arrays</module>
        <module>a_Fundamentals/c_HashTables</module>
        <module>a_Fundamentals/d_RecursionNbacktracking</module>
        <module>a_Fundamentals/e_Sorting</module>
        <module>b_CoreModule</module>
        <module>b_CoreModule/a_StackNQueue</module>
        <module>b_CoreModule/b_LinkedList</module>
        <module>b_CoreModule/c_Tree</module>
        <module>c_Advance</module>
        <module>c_Advance/a_DynamicProgramming</module>
        <module>a_Fundamentals/f_Searching</module>
    </modules>

    <properties>
        <maven.compiler.source>24</maven.compiler.source>
        <maven.compiler.target>24</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

</project>